FROM ubuntu:26.04 AS rootfs

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git curl wget build-essential ca-certificates openssh-client \
    python3-minimal \
    sudo \
    vim less file strace gdb \
    iproute2 iputils-ping dnsutils net-tools tcpdump \
    procps sysstat iptables nftables isc-dhcp-client \
    systemd systemd-sysv systemd-resolved dbus udev \
    e2fsprogs \
    linux-tools-common \
    podman buildah skopeo uidmap slirp4netns fuse-overlayfs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN printf '%s\n' \
    'deb http://ports.ubuntu.com/ubuntu-ports resolute main universe' \
    'deb http://ports.ubuntu.com/ubuntu-ports resolute-updates main universe' \
    > /etc/apt/sources.list

FROM ubuntu:26.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    e2fsprogs \
    && rm -rf /var/lib/apt/lists/*

COPY --from=rootfs / /rootfs

RUN truncate -s 4G /rootfs.ext4 && \
    mke2fs -F -t ext4 -b 16384 -d /rootfs -L lnx /rootfs.ext4
